export const courseSlugMap: Record<string, string> = {
  "ai-ml-internship": "dsa-ai-ml",
  "full-stack-development": "full-stack-development",
  cybersecurity: "cybersecurity-risk-management",
  "cloud-devops": "cloud-computing-devops",
  "digital-product-design": "digital-product-design",
  "embedded-systems-iot": "embedded-systems-iot",
  "semiconductor-vlsi": "semiconductor-vlsi",
  "ai-driven-electronics": "ai-driven-electronics",
  "ev-tech-battery": "ev-tech-battery",
  "industrial-automation": "industrial-automation",
  "renewable-energy": "renewable-energy",
  "product-design-manufacturing": "product-design-manufacturing",
  "robotics-automation": "robotics-automation",
  "electric-mobility-automotive": "electric-mobility-automotive",
  "digital-marketing-ai": "digital-marketing-ai",
  "business-development-sales": "business-development-sales",
  "hr-talent-acquisition": "hr-talent-acquisition",
  "financial-analytics": "financial-analytics",
};
